# 2.2) NumPy:  Creating Array


**Created by Vitor Kamada**

**Date:** 6/28/2019

In [0]:
import numpy as np

Let's create a matrix 2x3 with zeros:

In [0]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Let's create a sequence of numbers:




In [0]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

We can also use the function linspace():

In [0]:
np.linspace(1,9,5)

array([1., 3., 5., 7., 9.])

Let's create random values:

In [0]:
np.random.random((3,2))

array([[0.47335913, 0.00853873],
       [0.42665776, 0.74977086],
       [0.37441074, 0.95557596]])