# 2.3) NumPy:  Increment Operator


**Created by Vitor Kamada**

**Date:** 6/29/2019

In [0]:
import numpy as np

Let's create a sequence of numbers:

In [2]:
a = np.arange(4)
a

array([0, 1, 2, 3])

Let's add a scalar 1 element-wise:

In [3]:
a = a + 1
a

array([1, 2, 3, 4])

Let's use the increment operator "+=":

In [4]:
a += 1
a

array([2, 3, 4, 5])

Let's use the decrement  operator "-=":

In [5]:
a -= 1
a

array([1, 2, 3, 4])

Let's multiply element-wise:




In [6]:
a *= 3
a

array([ 3,  6,  9, 12])